# Update the params.yaml (do not leave it empty, otw error)

AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model (https://keras.io/api/applications/)
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01